export enum GameMap
{
	OLD_SUMMONERS_RIFT = 1,
	OLD_SUMMONERS_RIFT_AUTUMN = 2,
	TUTORIAL_MAP = 3,
	OLD_TWISTED_TREELINE = 4,

	CRYSTAL_SCAR = 8,

	// currently active
	TWISTED_TREELINE = 10,
	SUMMONERS_RIFT = 11,
	HOWLING_ABYSS = 12,

	BUTCHERS_BRIDGE = 14,
	COSMIC_RUINS = 16,
}
