export enum GameMode
{
	CLASSIC = 'CLASSIC',
	ODIN = 'ODIN',
	ARAM = 'ARAM',
	TUTORIAL = 'TUTORIAL',
	ONEFORALL = 'ONEFORALL',
	ASCENSION = 'ASCENSION',
	FIRSTBLOOD = 'FIRSTBLOOD',
	KINGPORO = 'KINGPORO',
	SIEGE = 'SIEGE',
	ASSASSINATE = 'ASSASSINATE',
	ARSR = 'ARSR',
	DARKSTAR = 'DARKSTAR',
}
