export enum LocalizationStrings
{
	PLUGIN_LEAGUE_LEVEL = 'PLUGIN_LEAGUE_LEVEL',
	PLUGIN_LEAGUE_LAST_UPDATE = 'PLUGIN_LEAGUE_LAST_UPDATE',
	PLUGIN_LEAGUE_LAST_PLAYED = 'PLUGIN_LEAGUE_LAST_PLAYED',
	PLUGIN_LEAGUE_TOTAL_MASTERY_POINTS = 'PLUGIN_LEAGUE_TOTAL_MASTERY_POINTS',
	PLUGIN_LEAGUE_MASTERY_POINTS_TO_NEXT_LEVEL = 'PLUGIN_LEAGUE_MASTERY_POINTS_TO_NEXT_LEVEL',
	PLUGIN_LEAGUE_CHAMPION_TOKEN_TO_NEXT_LEVEL = 'PLUGIN_LEAGUE_CHAMPION_TOKEN_TO_NEXT_LEVEL',
	PLUGIN_LEAGUE_MASTERY_CHEST_GRANTED = 'PLUGIN_LEAGUE_MASTERY_CHEST_GRANTED',
	PLUGIN_LEAGUE_MASTERY_PRESENTATION = 'PLUGIN_LEAGUE_MASTERY_PRESENTATION',
	PLUGIN_LEAGUE_PAGE_INDICATOR = 'PLUGIN_LEAGUE_PAGE_INDICATOR',
	PLUGIN_LEAGUE_PAGE_AUTHOR = 'PLUGIN_LEAGUE_PAGE_AUTHOR',
	PLUGIN_LEAGUE_TOTAL_MASTERY_LEVEL = 'PLUGIN_LEAGUE_TOTAL_MASTERY_LEVEL',
	PLUGIN_LEAGUE_CHAMPIONS_TOP_TEN = 'PLUGIN_LEAGUE_CHAMPIONS_TOP_TEN',
	PLUGIN_LEAGUE_CHAMPIONS_FROM_TO = 'PLUGIN_LEAGUE_CHAMPIONS_FROM_TO',
	PLUGIN_LEAGUE_NO_SUMMONER_FOUND = 'PLUGIN_LEAGUE_NO_SUMMONER_FOUND',
	PLUGIN_LEAGUE_NO_MASTERY_FOUND = 'PLUGIN_LEAGUE_NO_MASTERY_FOUND',
	PLUGIN_LEAGUE_RESOLVE_TWO_ARGS = 'PLUGIN_LEAGUE_RESOLVE_TWO_ARGS',
	PLUGIN_LEAGUE_RESOLVE_PAGE_OR_CHAMPION = 'PLUGIN_LEAGUE_RESOLVE_PAGE_OR_CHAMPION',

	// base string
	EXPECT_ERR_INVALID_OPTION = 'EXPECT_ERR_INVALID_OPTION',
}
